# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - acme

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    env: 
      ACME_DATASOURCE_URL: ${{ vars.ACME_DATASOURCE_URL }}
      ACME_DB_USERNAME: ${{ vars.ACME_DB_USERNAME }}
      ACME_DB_PASSWORD: ${{ secrets.ACME_DB_PASSWORD }}
      ACME_ALLOWED_ORIGINS: ${{ vars.ACME_ALLOWED_ORIGINS }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Restore certificates (write public and private PEM files)
        env:
          ACME_PUBLIC_KEY: ${{ vars.PUBLIC_PEM }}
          ACME_PRIVATE_KEY: ${{ secrets.PRIVATE_PEM }}
        run: |
          # create certs dir in resources so they are packaged on the classpath
          mkdir -p src/main/resources/certs

          # write the public key (repository variable) to public.pem
          printf '%s\n' "$ACME_PUBLIC_KEY" > src/main/resources/certs/public.pem

          # write the private key (secret) to private.pem
          # ensure no accidental output of the secret
          printf '%s\n' "$ACME_PRIVATE_KEY" > src/main/resources/certs/private.pem

          # secure permissions
          chmod 644 src/main/resources/certs/public.pem
          chmod 600 src/main/resources/certs/private.pem

          echo "Listing resources dir:"
          ls -la src/main/resources || true

          echo "Listing certs dir:"
          ls -la src/main/resources/certs || true

      - name: Copy application.properties template (placeholders left for runtime)
        run: |
          if [ -f src/main/resources/application.properties.template ]; then
            cp src/main/resources/application.properties.template src/main/resources/application.properties
          else
            echo "WARNING: application.properties.template not found; skipping copy."
          fi
          
      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_721F2F47D09E49718DBFCAFD01D0001F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CD81120201284E1794ED0C73937D2624 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0B751F37066049A19B89BEB44102FA66 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'acme'
          slot-name: 'Production'
          package: '*.jar'

          




